// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDZWxXIozQGoo8prR11aw70O5o1cfib0s',
    appId: '1:944248096163:web:3814baca3fc44b7458c616',
    messagingSenderId: '944248096163',
    projectId: 'flutter-chat-a6985',
    authDomain: 'flutter-chat-a6985.firebaseapp.com',
    databaseURL: 'https://flutter-chat-a6985-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-a6985.appspot.com',
    measurementId: 'G-LNY9MLBL5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhipG5skzhiPaDBtT_PrG1GHY-eZDH65s',
    appId: '1:944248096163:android:b2dffd6b0c94471458c616',
    messagingSenderId: '944248096163',
    projectId: 'flutter-chat-a6985',
    databaseURL: 'https://flutter-chat-a6985-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-a6985.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASj9s_VuKhPvV2oopubxlv0iCOdV0Wvvw',
    appId: '1:944248096163:ios:cac1201a638c84c658c616',
    messagingSenderId: '944248096163',
    projectId: 'flutter-chat-a6985',
    databaseURL: 'https://flutter-chat-a6985-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-a6985.appspot.com',
    iosClientId: '944248096163-atb62g0m8bem1emr48s6107si1a9schf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
